parameters:
    evolution.security.authentication.listener.class: Theodo\Evolution\SecurityBundle\Firewall\Listener\VendorSpecific\Symfony10SecurityListener
    evolution.security.authentication.provider.class: Theodo\Evolution\SecurityBundle\Authentication\Provider\AuthenticationProvider
    evolution.security.user_provider.class:           Theodo\Evolution\SecurityBundle\UserProvider\UserProvider

services:
    evolution.security.authentication.listener:
        class: %evolution.security.authentication.listener.class%
        public: false
        arguments:
            - @security.context
            - @security.authentication.manager
            - @evolution.session.bag_manager_configuration
            - @?logger

    evolution.security.authentication.provider:
        class: %evolution.security.authentication.provider.class%
        arguments:
            - @evolution.security.user_provider

    evolution.security.user_provider:
        class: %evolution.security.user_provider.class%
        arguments:
            - @evolution.security.legacy_user_repository

    evolution.security.encoder:
        class: %evolution.security.encoder.class%
        arguments:
            - %theodo.evolution.security.encoder.algorithm%
