parameters:
    evolution.security.authentication.listener.class: Theodo\Evolution\SecurityBundle\Firewall\Listener\SecurityListener
    evolution.security.authentication.provider.class: Theodo\Evolution\SecurityBundle\Authentication\Provider\AuthenticationProvider
    evolution.security.user_provider.class:           Theodo\Evolution\SecurityBundle\UserProvider\UserProvider

    evolution.security.authentication.symfony10_entry_point.class: Theodo\Evolution\SecurityBundle\EntryPoint\Symfony10EntryPoint

services:
    evolution.security.authentication.listener:
        class: %evolution.security.authentication.listener.class%
        public: false
        arguments:
            - @security.context
            - @security.authentication.manager
            - @evolution.session.bag_manager_configuration
            - @?logger

    evolution.security.authentication.provider:
        class: %evolution.security.authentication.provider.class%
        arguments:
            - @evolution.security.user_provider

    evolution.security.user_provider:
        class: %evolution.security.user_provider.class%
        arguments:
            - @evolution.security.legacy_user_repository

    evolution.security.authentication.entry_point:
        class: %evolution.security.authentication.entry_point.class%
        public: false
        arguments:
            - ''
            - @session
            - @evolution.session.bag_manager_configuration
