language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

#env:
#    - SYMFONY_VERSION=2.2.*
#    - SYMFONY_VERSION=2.3.*
#    - SYMFONY_VERSION=2.4.*
#    - SYMFONY_VERSION=dev-master

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master

before_script:
    - composer self-update
    - composer update --dev

script: phpunit --coverage-text

notifications:
  email:
    - open-source@theodo.fr
